# version: "3.8"

# services:
#   web:
#     build: .
#     networks:
#       - journal_default
#     ports:
#       - "5433:5432"
#     environment:
#       - DB_URL=postgresql://postgres:linky1337@172.17.0.1:5432/DevOps
#     depends_on:
#       - DevOps
#   DevOps:
#     container_name: DevOps
#     image: postgres:16
#     ports:
#       - "5433:5432"
#     environment:
#       - POSTGRES_PASSWORD=linky1337
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=DevOps
#     volumes:
#       - pgdata:/var/lib/postgresql/data
# networks:
#   journal_default:
#     driver: bridge
# volumes:
#   pgdata: {}
version: "3.8"
services:
  web:
    build: .
    links:
      - "postgres_db:adminer"
    container_name: DevOps_app
    restart: always
    ports:
      - 5000:5000
    environment:
      - DEBUG=0 
    depends_on:
      - postgres_db
      - adminer
    env_file:
      - ./app/.env
    volumes:
      - ./app:/code
  
  adminer:
    image: adminer
    container_name: adminer_psql
    restart: always
    ports:
      - 8080:8080     

  postgres_db:
    build: 
      context: ./database
      dockerfile: Dockerfile
    container_name: PostgresCont
    ports:
      - 5432:5432
    restart: "unless-stopped"
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local